"""
FastAPI dependencies.

User identity uses a silent header-based approach:
  X-Device-ID       — UUID generated by the iOS app (persisted in Keychain)
  X-CloudKit-ID     — CloudKit record ID (preferred when iCloud is available)

On first call, a User row is created. Subsequent calls find it by the same header.
No login required.
"""
from fastapi import Header, HTTPException, Depends
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.database import get_db
from app.models.user import User
import uuid


async def get_current_user(
    db: AsyncSession = Depends(get_db),
    x_device_id: str | None = Header(default=None),
    x_cloudkit_id: str | None = Header(default=None),
) -> User:
    if not x_device_id and not x_cloudkit_id:
        raise HTTPException(status_code=401, detail="Missing X-Device-ID or X-CloudKit-ID header")

    # Prefer CloudKit ID if provided
    if x_cloudkit_id:
        result = await db.execute(select(User).where(User.cloudkit_record_id == x_cloudkit_id))
        user = result.scalar_one_or_none()
        if not user:
            user = User(
                id=str(uuid.uuid4()),
                cloudkit_record_id=x_cloudkit_id,
                device_id=x_device_id,
            )
            db.add(user)
            await db.commit()
            await db.refresh(user)
        elif x_device_id and not user.device_id:
            user.device_id = x_device_id
            await db.commit()
        return user

    # Fallback to device ID
    result = await db.execute(select(User).where(User.device_id == x_device_id))
    user = result.scalar_one_or_none()
    if not user:
        user = User(id=str(uuid.uuid4()), device_id=x_device_id)
        db.add(user)
        await db.commit()
        await db.refresh(user)
    return user
